export const beerList: string[] = [
  "Ace Cider",
  "All Day IPA",
  "ALLEY CAT",
  "AMSTEL LIGHT",
  "ANCHOR STEAM",
  "Angry Orchard",
  "Asylum Tripel",
  "Aunt Sally",
  "Beach Blonde Ale",
  "Bell Cow Porter",
  "Bells Amber Ale",
  "BFD",
  "Bitches Brew",
  "BLITHERING IDIOT",
  "Blood Red Sky Ale",
  "Blue Moon Bottle",
  "Boddingtons",
  "Boom Sauce",
  "Breckinridge Van Por",
  "Bud Light LIME",
  "Buried Hatchet",
  "Cloud Chaser",
  "Coors N/A",
  "CORONA",
  "CORONA LIGHT",
  "Day Glow Ipa",
  "Dirty Bastard",
  "Dogfish Head",
  "DOS XX AMBER ALE",
  "DOS XX LAGER",
  "Double Trouble Ipa",
  "Downtown Brown",
  "Dragons Milk",
  "Dragons Yumyums",
  "Einstok Porter",
  "Erdinger Weissbier",
  "Fat Tire 12oz",
  "Flensburger",
  "Florida Cracker",
  "Founders B Stout",
  "Founders Porter",
  "Full Sail lager",
  "Funky Buddha",
  "Goin Coastal",
  "Goose Island Ipa",
  "GREAT WHITE",
  "GROLSCH SWING TOP",
  "Guinness Foreign",
  "Hacker Pschorr Octob",
  "HARP",
  "HEINEKEN",
  "Hevelius Kaper",
  "Highland Gaelic Ale",
  "Hofbrau",
  "Hop gun Ipa",
  "Hoptimum Ipa",
  "Innis and Gunn",
  "Invasion Pale Ale",
  "Jam Band Ale",
  "KALIK",
  "KILLIANS",
  "KONA BIG WAVE",
  "KONA LONGBOARD",
  "Kronenburg 1664",
  "La Fin Du Monde",
  "Labatt Blue",
  "Lagunitas",
  "Leffe",
  "Leinenkugals Shandy",
  "Lexington Bourbo Ale",
  "Lil Sumpthin",
  "Maduro Brown Ale",
  "Magic Hat #9",
  "Magners Pear",
  "McKenzie Cider",
  "MERRY MONK'S ALE",
  "Mia Mega Mix",
  "MODELLO ESPECIAL",
  "MOLSON CANADIAN",
  "MONTY PYTH HOLY AIL",
  "MOOSEHEAD",
  "Naked Truth Ipa",
  "NEGRO MODELLO",
  "Neopolitan Stout",
  "NEWCASTLE",
  "Oatmeal Raisin Ale",
  "OBP Squared",
  "Orange Blosm Pils",
  "PABST BLU R Tall Boy",
  "PALMA LOUCA",
  "PERONI",
  "Poolside Kolsch",
  "Prairie Path Ale",
  "Pumpkinhead",
  "Purple Haze by Abita",
  "RED STRIPE",
  "Rekorderlig cider",
  "Resin Ipa",
  "ROLLING ROCK",
  "ROUGE Ale",
  "SAM ADAMS Seasonal",
  "Sam Smith Milk Choc",
  "SAMUEL ADAMS",
  "Schofferhofer",
  "Sculpin IPA",
  "Sea Cow Stout",
  "Sea Dog",
  "Seagrams Cooler",
  "Shake Porter",
  "SHINER BOCK",
  "SIERRA NEV Pale Ale",
  "Sixth Glass Quad",
  "Smithwicks",
  "Space Dust Ipa",
  "St peters porter",
  "Stella Artois",
  "Strongbow",
  "Superfuzz",
  "SWEET BABY JESUS",
  "Sweetwater 420",
  "TAJ MAHAL Large",
  "Tangerine Wheat",
  "Tank 7",
  "Terrapin Ale",
  "Toasted Lager",
  "Trickster Ipa",
  "Tucher DARK",
  "Tucher LIGHT",
  "Two Hearted Ale",
  "UFO Pineapple",
  "Unholy Tripel",
  "Urquell",
  "Victory Dirt Wolf",
  "Warstiener",
  "WEIHENSTEPHAN",
  "Wells Banana Bread",
  "White Claw",
  "WITTEKERKE",
  "Wolf Pup Ipa",
  "Yeungling Blk n Tan",
];
